<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="telephone=no" name="format-detection">
    <title></title>
    <!--[if (mso 16)]>
    <style type="text/css">
        a {text-decoration: none;}
    </style>
    <![endif]-->
    <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->
    <!--[if !mso]><!-- -->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,700,700i" rel="stylesheet">
    <!--<![endif]-->
</head>

<body>
<div class="es-wrapper-color">
    <!--[if gte mso 9]>
    <v:background xmlns:v="urn:schemas-microsoft-com:vml" fill="t">
        <v:fill type="tile" color="#555555"></v:fill>
    </v:background>
    <![endif]-->
    <table class="es-wrapper" width="100%" cellspacing="0" cellpadding="0">
        <tbody>
        <tr>
            <td class="esd-email-paddings" valign="top">
                <table cellpadding="0" cellspacing="0" class="es-content esd-header-popover" align="center">
                    <tbody>
                    <tr>
                        <td class="esd-stripe" align="center" esd-custom-block-id="88701">
                            <table class="es-content-body" style="background-color: transparent;" width="600" cellspacing="0" cellpadding="0" align="center">
                                <tbody>
                                <tr>
                                    <td class="esd-structure es-p5b es-p10r es-p10l" esd-general-paddings-checked="false" align="left">
                                        <!--[if mso]><table width="580" cellpadding="0" cellspacing="0"><tr><td width="280" valign="top"><![endif]-->

                                        <!--[if mso]></td><td width="20"></td><td width="280" valign="top"><![endif]-->

                                        <!--[if mso]></td></tr></table><![endif]-->
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <table class="es-header" cellspacing="0" cellpadding="0" align="center">
                    <tbody>
                    <tr>
                        <td class="esd-stripe" align="center">
                            <table class="es-header-body" style="background-color: #f4f4f4;" width="600" cellspacing="0" cellpadding="0" bgcolor="#f4f4f4" align="center">
                                <tbody>

                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <table class="es-content" cellspacing="0" cellpadding="0" align="center">
                    <tbody>
                    <tr>
                        <td class="esd-stripe" align="center">
                            <table class="es-content-body" style="background-color: #b3e0f5;" width="600" cellspacing="0" cellpadding="0" bgcolor="#b3e0f5" align="center">
                                <tbody>
                                <tr>
                                    <td class="esd-structure" style="background-repeat: no-repeat;" align="left">
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                            <tr>
                                                <td class="esd-container-frame" width="600" valign="top" align="center">
                                                    <table width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-image" align="center" style="font-size:0"><a target="_blank"><img class="adapt-img" src="https://tlr.stripocdn.email/content/guids/CABINET_25c7169da4008a02e0cf94e30016f268/images/15041521718233205.jpg" alt style="display: block;" height="121"></a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="esd-structure es-p20r es-p20l" style="background-repeat: no-repeat;" align="left">
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                            <tr>
                                                <td class="esd-container-frame" width="560" valign="top" align="center">
                                                    <table width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-text" align="center">
                                                                <h1 style="color: #ffffff; font-family: lora, georgia, times\ new\ roman, serif; font-size: 48px; line-height: 120%;"><em>${user.name}</em><br></h1>
                                                                <h1 style="color: #ffffff; font-family: lora, georgia, times\ new\ roman, serif; font-size: 25px; line-height: 120%;"><em><a target="_blank" href="http://localhost:80/confirm/${user.confirmCode}">${user.confirmCode}</a>
                                                                </em></h1>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="esd-block-text es-p20t es-p30b es-p10r es-p10l" align="center">
                                                                <h3 style="color: #ffffff; line-height: 150%;">We are giving our loyal customers 25% off. In store & online. Use code: EASTER18.<br></h3>
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="esd-structure es-p10t es-p10b es-p20r es-p20l" align="left">
                                        <!--[if mso]><table width="560" cellpadding="0"
                                                            cellspacing="0"><tr><td width="194" valign="top"><![endif]-->
                                        <table class="es-left" cellspacing="0" cellpadding="0" align="left">
                                            <tbody>
                                            <tr>
                                                <td class="es-m-p0r es-m-p20b esd-container-frame" width="174" align="center">
                                                    <table class="es-table-not-adapt" width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-banner" style="position: relative;" align="center" esdev-config="h4"><a target="_blank" href="https://viewstripo.email/"><img class="adapt-img esdev-stretch-width esdev-banner-rendered" src="https://tlr.stripocdn.email/content/guids/bannerImgGuid/images/59321556290315936.png" alt="20% off for mobiles" title="20% off for mobiles" style="display: block;" width="174"></a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                                <td class="es-hidden" width="20"></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <!--[if mso]></td><td width="173" valign="top"><![endif]-->
                                        <table class="es-left" cellspacing="0" cellpadding="0" align="left">
                                            <tbody>
                                            <tr>
                                                <td class="es-m-p20b esd-container-frame" width="173" align="center">
                                                    <table class="es-table-not-adapt" width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-banner" style="position: relative;" align="center" esdev-config="h5"><a target="_blank" href="https://viewstripo.email/"><img class="adapt-img esdev-stretch-width esdev-banner-rendered" src="https://tlr.stripocdn.email/content/guids/bannerImgGuid/images/71131521728568959.png" alt="20% off for memory" title="20% off for memory" style="display: block;" width="173"></a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <!--[if mso]></td><td width="20"></td><td width="173" valign="top"><![endif]-->
                                        <table class="es-right" cellspacing="0" cellpadding="0" align="right">
                                            <tbody>
                                            <tr>
                                                <td class="esd-container-frame" width="173" align="center">
                                                    <table class="es-table-not-adapt" width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-banner" style="position: relative;" align="center" esdev-config="h6"><a target="_blank" href="https://viewstripo.email/"><img class="adapt-img esdev-stretch-width esdev-banner-rendered" src="https://tlr.stripocdn.email/content/guids/bannerImgGuid/images/17711531914196184.png" alt="20% off for headphones" title="20% off for headphones" style="display: block;" width="173"></a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <!--[if mso]></td></tr></table><![endif]-->
                                    </td>
                                </tr>
                                <tr>
                                    <td class="esd-structure esd-checked es-p20t es-p40b es-p20r es-p20l" style="background-image:url(https://tlr.stripocdn.email/content/guids/CABINET_25c7169da4008a02e0cf94e30016f268/images/14101521723753926.png);background-repeat: no-repeat; background-position: left top;" align="left">

                                    </td>
                                </tr>
                                <tr>
                                    <td class="esd-structure" align="left">
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                            <tr>
                                                <td class="esd-container-frame" width="600" valign="top" align="center">
                                                    <table width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-image" align="left" style="font-size:0"><a target="_blank"><img class="adapt-img" src="https://tlr.stripocdn.email/content/guids/CABINET_25c7169da4008a02e0cf94e30016f268/images/97471521717404592.png" alt style="display: block;" height="55"></a></td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <table cellpadding="0" cellspacing="0" class="es-footer" align="center">
                    <tbody>
                    <tr>
                        <td class="esd-stripe" align="center" esd-custom-block-id="88707">
                            <table class="es-footer-body" width="600" cellspacing="0" cellpadding="0" align="center">
                                <tbody>
                                <tr>
                                    <td class="esd-structure es-p20" esd-general-paddings-checked="false" align="left">
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tbody>
                                            <tr>
                                                <td class="esd-container-frame" width="560" valign="top" align="center">
                                                    <table width="100%" cellspacing="0" cellpadding="0">
                                                        <tbody>
                                                        <tr>
                                                            <td class="esd-block-social es-p10t es-p20b" align="center" style="font-size:0">
                                                                <table class="es-table-not-adapt es-social" cellspacing="0" cellpadding="0">
                                                                    <tbody>
                                                                    <tr>
                                                                        <td class="es-p15r" valign="top" align="center"><a href><img title="Twitter" src="https://stripo.email/cabinet/assets/editor/assets/img/social-icons/circle-gray/twitter-circle-gray.png" alt="Tw" width="32" height="32"></a></td>
                                                                        <td class="es-p15r" valign="top" align="center"><a href><img title="Facebook" src="https://stripo.email/cabinet/assets/editor/assets/img/social-icons/circle-gray/facebook-circle-gray.png" alt="Fb" width="32" height="32"></a></td>
                                                                        <td class="es-p15r" valign="top" align="center"><a href><img title="Youtube" src="https://stripo.email/cabinet/assets/editor/assets/img/social-icons/circle-gray/youtube-circle-gray.png" alt="Yt" width="32" height="32"></a></td>
                                                                        <td valign="top" align="center"><a href><img title="Linkedin" src="https://stripo.email/cabinet/assets/editor/assets/img/social-icons/circle-gray/linkedin-circle-gray.png" alt="In" width="32" height="32"></a></td>
                                                                    </tr>
                                                                    </tbody>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td align="center" class="esd-block-text">

                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td class="esd-block-text es-p10t es-p10b" align="center">

                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                    </tbody>
                </table>

            </td>
        </tr>
        </tbody>
    </table>
</div>
</body>

</html>